# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kista-lunch-api

on:
  push:
    branches:
      - api-deployment-ready
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e346ed9a021f4407b054c93a0136322b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fcf5709ede5d4847ab439d831aa7e8ac }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e346ed9a021f4407b054c93a0136322b }}/ecalbre/lunch_api:${{ github.sha }}
        context: ./api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kista-lunch-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1d2ef432f8144cd08cb14e39fe4d1245 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e346ed9a021f4407b054c93a0136322b }}/ecalbre/lunch_api:${{ github.sha }}'